# Generated by Django 2.2.14 on 2021-05-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('house_type', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('area', models.IntegerField()),
                ('bedrooms', models.CharField(max_length=10)),
                ('owner_name', models.CharField(max_length=100)),
                ('owner_mobile', models.CharField(max_length=12)),
                ('rent', models.DecimalField(decimal_places=2, max_digits=65)),
            ],
            options={
                'db_table': 'houses_orders',
            },
        ),
    ]
