# Generated by Django 2.2.14 on 2021-05-18 05:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_customer', '0002_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housecustomer',
            name='mobileno',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(limit_value=10), django.core.validators.MaxLengthValidator(limit_value=10)]),
        ),
        migrations.AlterField(
            model_name='housecustomer',
            name='password',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(limit_value=6)]),
        ),
        migrations.AlterField(
            model_name='orders',
            name='owner_mobile',
            field=models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(limit_value=10), django.core.validators.MaxLengthValidator(limit_value=10)]),
        ),
    ]
