# Generated by Django 2.2.14 on 2021-05-17 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house_owner', '0005_houses_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='houses',
            name='category',
        ),
    ]
