# Generated by Django 2.2.14 on 2021-05-18 05:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_owner', '0007_auto_20210518_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseowner',
            name='mobileno',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(limit_value=10), django.core.validators.MaxLengthValidator(limit_value=10)]),
        ),
    ]
